### ISSUE TITLE
Automated BGP interoperability testing

### ISSUE THREAD

**Issue by rcgoodfellow** [oxidecomputer/maghemite#98]
All of the interoperability testing I'm doing for BGP is currently manual. That's not sustainable. We need an automated approach to interoperability testing that can run in CI.

- [x] Arista EOS
- [ ] Cisco IOS
- [ ] Juniper Junos
- [ ] SRLinux
- [x] FRR
- [ ] Google Cloud Router

**Comment by taspelund** [comment]
Was this ticket addressed by #466 or do we want this to stay open until the interop topology supports all the vendors listed above?

**Comment by rcgoodfellow** [comment]
#466 got us going in CI. We still have a lot to do for the interoperability testing itself. Making sure that the various BGP capabilities we implement that depend on interoperability such route refresh, md5 protected sessions, etc. work with the major vendors.
